version: "3.8"

services:
  airflow:
    build:
      context: ./airflow
    container_name: airflow_mlops
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/app/dags
    command: >
      bash -c "pip install apache-airflow && airflow db init && airflow users create 
      --username admin --password admin --firstname Ayoub --lastname Admin --role Admin --email admin@example.com &&
      airflow scheduler & airflow webserver"
